spring.application.name=D1-UD4

spring.datasource.url=jdbc:mysql://localhost/dwes3
spring.datasource.username=daw2
spring.datasource.password=LaElipa

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update